# Ativa os logs de Debug
DEBUG = false
DEBUG_ALCHEMY = false

[database]
DATABASE = "lab_web"
HOST = "localhost"
PORT = 3306
USERNAME = "root"

[JWT]
# Segurança do JWT (JSON Web Token)
# Use 'openssl rand -hex 32' para gerar uma chave segura
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30 # O token expira em 30 minutos
